### ISSUE TITLE
Error thrown whenever auto-swap toggled off while coin in swap

### ISSUE THREAD

**Issue by sgershuny** [layer2tech/mercury-wallet#1089]
![image](https://user-images.githubusercontent.com/72019925/148547347-f9f6decf-7b65-4e06-94c7-83b14e8812df.png)

The intention of the user was not to remove the coin from swap but toggle off the auto-swap feature.

**Comment by tomt1664** [comment]
Still useful info IMO - but should be warning instead of error.
