### ISSUE TITLE
Coin changed to available while previously in a swap, now cannot swap

### ISSUE THREAD

**Issue by rk16449** [layer2tech/mercury-wallet#1172]
SWAPS require swap.statecoin.status to be in state STATECOIN_STATUS.AWAITING_SWAP, at some point during swaps this coin changes to STATECOIN_STATUS.AVAILABLE and is unable to swap while having the appearance of trying to swap.

- will catch an  error in resume swap
- there was a fail to the api call deregister swap in network which may have caused this

**Comment by lawlawlaw** [comment]
Fixed with pull request https://github.com/layer2tech/mercury-wallet/pull/1174
