### ISSUE TITLE
Swap sampler

### ISSUE THREAD

**Issue by nicosey** [layer2tech/mercury-wallet#1181]
Would like a feature where we can sample the participation in a swap.
For example, if I click on the auto swap, with an auto swap of 1 is set, the auto swap feature would skip a swap every 1 time.  If the sample rate was set to 2 it would skip 2 swaps.
The sampler rate could be set under settings, with the default being 0.

**Comment by tomt1664** [comment]
The alternative idea is to have a switch in the settings that limits the wallet to entering only a single coin of a specific amount into a swap at any one time. When the switch is on, and multiple coins of the same value are put on autoswap, only one (initially, only the first one turned on autoswap) joins a group. 

Only after the first coin completes a swap, it deregisters, and then the next of the coins is registered instead. Once this completes a swap, the next one is registered, and so on.

**Comment by lawlawlaw** [comment]
This feature was included in version 0.6.5.
