### ISSUE TITLE
Memory Leak Warning

### ISSUE THREAD

**Issue by sgershuny** [layer2tech/mercury-wallet#1208]
2 Statecoins on phase 6/8 in swap together
Then I tried to send a SC to the latest address in my wallet
got this error:

![image](https://user-images.githubusercontent.com/72019925/154277279-b646d24a-3355-4a60-bcdb-199dfcbe9a92.png)

**Comment by sgershuny** [comment]
![image](https://user-images.githubusercontent.com/72019925/154297963-1d2fa2e4-2b0b-480f-b14c-943c151dd6ff.png)

Happened again on transfer send

**Comment by lawlawlaw** [comment]
Fixed with pull request https://github.com/layer2tech/mercury-wallet/pull/1232
