### ISSUE TITLE
Backuptx Page enhancements

### ISSUE THREAD

**Issue by 86667** [layer2tech/mercury-wallet#121]
It would be good to have a status indication (not-broadcast/pre-locktime, broadcast but unconfirmed - WARNING/RED, broadcast and unconfirmed but previous owner nLokctime reached - VERRY BAD/REDDER, and confirmed).

Also would be nice to have some kind of 'reveal' button for the privkey.

**Comment by tomt1664** [comment]
Also fixing the text boxes to enter the address and fee rate for CPFP - not displaying nicely.

**Comment by tomt1664** [comment]
![Screenshot 2021-05-04 at 23 59 05](https://user-images.githubusercontent.com/15906918/117080503-e0b8a000-ad35-11eb-8614-0b87587d9329.png)

**Comment by tomt1664** [comment]
For the backup transaction details window on the right (which shows the details for the statecoin selected on the left). 

1. Remove the 'Months left' label and item. 
2. Remove the 'Private key hex' label and item. 
3. The 'Private key WIF' value should be replaced with a 'Show' button. When pressed, this button should open a box which shows the key (e.g. cRKm8bcc...) and a QR code for the key. 
4. If the 'Status' value is 'Confirmed' the text should be bold green with a checkmark symbol &#9989;
5. If the 'Status' value is 'Unbroadcast' or 'In mempool' or 'Interval elapsed' the text should be bold orange with a warning symbol &#9888;
6. If the 'Status' value is 'Taken' the text should be bold red with a failed symbol &#10062;
7. The 'Pay to:' and 'Fee' text boxes should be standard text boxes (smaller height with no border text). 
8. 'CREATE CPFP' button right justified.

**Comment by alexyjs** [comment]
> It would be good to have a status indication (not-broadcast/pre-locktime, broadcast but unconfirmed - WARNING/RED, broadcast and unconfirmed but previous owner nLokctime reached - VERRY BAD/REDDER, and confirmed).
> 

Do we have any design for this?

I can access this status same as coin status via “backup_status” property, right?

And I can’t found the design of Backup Transaction page. Do you know where is it?
