### ISSUE TITLE
Not connecting to Server, not connecting to Swaps, not connecting to Bitcoin

### ISSUE THREAD

**Issue by jonmatonis** [layer2tech/mercury-wallet#1215]
Endless loop on attempting to connect to Server after upgrading to version 0.6.4

**Comment by rk16449** [comment]
Could also be that an anti-virus is blocking connections

**Comment by jonmatonis** [comment]
Corrected by a PC reboot. Thank you.

There is still the issue of "Expired coins are unavailable for transfer, swap and withdrawal" with 3 days until expiry [this is on Windows 10 platform].

**Comment by tomt1664** [comment]
The issue should be fixed in the latest release here: https://github.com/layer2tech/mercury-wallet/releases/tag/v0.6.5

Let us know if you still can't withdraw.

**Comment by jonmatonis** [comment]
Installed v0.6.5 and withdraw still not possible. Additional feature from the upgrade now turned my 1 statecoin into 14 statecoins showing total balance of .014

**Comment by rk16449** [comment]
0.6.6 should fix the windows issue without having to restart your pc. This topic has changed to withdrawing coins - see  new issue related to this #1248 1248
