### ISSUE TITLE
Coin won't register for swap

### ISSUE THREAD

**Issue by nicosey** [layer2tech/mercury-wallet#1217]
![Screenshot 2022-02-19 at 10 59 22](https://user-images.githubusercontent.com/7435272/154798229-d3bd8ee2-7219-42e6-b115-12d5bc46e55b.png)

Coin is permanently not able to join swap.  Getting type error.

**Comment by lawlawlaw** [comment]
Fixed in pull request https://github.com/layer2tech/mercury-wallet/pull/1059
