### ISSUE TITLE
Coins no in pool, but when taken out on AutoSwap it displays error message.

### ISSUE THREAD

**Issue by nicosey** [layer2tech/mercury-wallet#1227]
![Screenshot 2022-02-22 at 07 51 42](https://user-images.githubusercontent.com/7435272/155087058-e96e713f-6cde-44c4-a36c-4f9592db40f4.png)

**Comment by lawlawlaw** [comment]
Fixed in pull request https://github.com/layer2tech/mercury-wallet/pull/1229
