### ISSUE TITLE
Withdrawal tx confirmation loop continues after transaction already confirmed

### ISSUE THREAD

**Issue by lawlawlaw** [layer2tech/mercury-wallet#1234]
In testnet, 2 coins of value 0.01 each were withdrawn. The withdrawal confirmation loop continues after the transation has been confirmed.

I don't know currently if this issue also occurs with withdrawal of a single statecoin.

See the console output below.

![multipleWithdrawalConfirmations](https://user-images.githubusercontent.com/4256700/155335479-3a0f1ee2-995d-4c15-83bc-c823cdfaf021.png)

**Comment by tomt1664** [comment]
Can you repost the image?

**Comment by tomt1664** [comment]
Did withdraw confirm properly (i.e. coins got to WITHDRAWN)?

**Comment by lawlawlaw** [comment]
> Can you repost the image?

Done

**Comment by lawlawlaw** [comment]
> Did withdraw confirm properly (i.e. coins got to WITHDRAWN)?

Yes - they are listed under the "withdrawn" tab.
