### ISSUE TITLE
withdraw still not possible

### ISSUE THREAD

**Issue by rk16449** [layer2tech/mercury-wallet#1248]
Installed v0.6.5 and withdraw still not possible. Additional feature from the upgrade now turned my 1 statecoin into 14 statecoins showing total balance of .014

_Originally posted by @jonmatonis in https://github.com/layer2tech/mercury-wallet/issues/1215#issuecomment-1048609054_

**Comment by tomt1664** [comment]
fixed with https://github.com/layer2tech/mercury-wallet/pull/1241
