### ISSUE TITLE
Duplicates in Activity

### ISSUE THREAD

**Issue by nicosey** [layer2tech/mercury-wallet#1261]
Bug from Activity view as you can see upon creation same ID is listed multiple times.

![Screenshot 2022-02-27 at 21 52 31](https://user-images.githubusercontent.com/7435272/155901439-96f1eee0-021b-49de-9eb7-5f8fb271e1bc.png)

**Comment by rk16449** [comment]
Exactly the same activity items are now removed, however similar items with the same tx_id and tx_vout and action but having a different date are not removed as they are still seen as unique from one another.

**Comment by lawlawlaw** [comment]
This issue is back - the same withdrawal is listed as multiple different withdrawals due to the fact that the date recorded is the date at the time of withdrawal confirmation.
