### ISSUE TITLE
Coin that has been with drawn and suitable for swaps, shows in swap selection and can be enabled

### ISSUE THREAD

**Issue by nicosey** [layer2tech/mercury-wallet#1264]
![Screenshot 2022-02-28 at 07 45 36](https://user-images.githubusercontent.com/7435272/155944058-70493e7a-0dce-4981-9e03-90a5993456f0.png)

**Comment by nicosey** [comment]
So seems this is more an issue of it showing up in swaps tab, 
I found the statecoin in main page.

**Comment by tomt1664** [comment]
Only allow coin to be selected if amount on group info list.
