### ISSUE TITLE
bug open for the "sing swap mode" stuff

### ISSUE THREAD

**Issue by nicosey** [layer2tech/mercury-wallet#1270]
![Screenshot 2022-03-01 at 16 55 52](https://user-images.githubusercontent.com/7435272/156213913-e1baed46-88d8-4809-b53c-41deebcfc692.png)

3 swaps have happened and other coin is not participating.

**Comment by lawlawlaw** [comment]
> ![Screenshot 2022-03-01 at 16 55 52](https://user-images.githubusercontent.com/7435272/156213913-e1baed46-88d8-4809-b53c-41deebcfc692.png)
> 
> 3 swaps have happened and other coin is not participating.

Are you sure the coin marked 'original' has not participated in swaps? In the main page, can you click on the coin marked 'original' and tell me the number of swap rounds shown?

**Comment by lawlawlaw** [comment]
> ![Screenshot 2022-03-01 at 17 02 29](https://user-images.githubusercontent.com/7435272/156214434-dd47d122-dd2d-4798-9a1b-91b59163a76b.png) More odd behaviour

What actions led to this? Did you change the 'single swap mode' setting to on after coins had already been registered for swaps? Coins already registered will complete their swaps before joining the queue.
