### ISSUE TITLE
A statecoin has been withdrawn in testnet but is still in the wallet and can still be recovered. 

### ISSUE THREAD

**Issue by lawlawlaw** [layer2tech/mercury-wallet#1331]
In a current development version of the wallet.
The coin cannot be sent - attempting to transfer results in the error shown below.
Statecoin UTXO output ID: 7405c4f890b819851b18155c260cab0cd791c377739ace3e225bfd2c082c4722:1 
<img width="1201" alt="Screenshot 2022-03-11 at 16 28 47" src="https://user-images.githubusercontent.com/4256700/157917057-ad04af7b-3bff-4543-b5e8-b7a904c4aa5b.png">

**Comment by tomt1664** [comment]
https://github.com/commerceblock/mercury/issues/330
