### ISSUE TITLE
Activity log issue

### ISSUE THREAD

**Issue by nicosey** [layer2tech/mercury-wallet#1333]
The activity log seems to delete older issues
I has some activity on two days ago, however after activity today the history was deleted and only new activity shown.

![Screenshot 2022-03-13 at 16 40 49](https://user-images.githubusercontent.com/7435272/158069869-a00a05de-4e9f-4af3-896d-36c4e28d6ef8.png)
![Screenshot 2022-03-13 at 16 40 49](https://user-images.githubusercontent.com/7435272/158069877-d95a40b7-4c51-4b40-b945-8e63712b4a74.png)

**Comment by lawlawlaw** [comment]
Fixed in pull request https://github.com/layer2tech/mercury-wallet/pull/1340
