### ISSUE TITLE
Deprecated error

### ISSUE THREAD

**Issue by nicosey** [layer2tech/mercury-wallet#1335]
Getting this in logs

"Deprecation Warning: TransactionBuilder will be removed in the future. (v6.x.x or later) Please use the Psbt class instead. Examples of usage are available in the transactions-psbt.js integration test file on our Github. A high level explanation is available in the psbt.ts and psbt.js files as well."

**Comment by tomt1664** [comment]
Suppress bitcoin js warnings.

**Comment by lawlawlaw** [comment]
Fixed in #1341
