### ISSUE TITLE
Wallet backup default filename (.json) in Windows contains invalid characters

### ISSUE THREAD

**Issue by Cepator** [layer2tech/mercury-wallet#1350]
Hi there,

While trying to create a backup of my wallet in Windows 10, I am getting "The filename is not valid." message due to invalid characters used in the default filename.

Please see the screenshots below.

![image](https://user-images.githubusercontent.com/90608723/159024739-15f07ed5-cbd1-416c-a850-4a8717e8ed38.png)
![image](https://user-images.githubusercontent.com/90608723/159024939-b2ac4139-b9fb-43b3-a5f5-baebca374d78.png)

I believe that this could be confusing for some users who may not realize that they need to change this default filename before saving it.

Thanks.
Regards,
Cepator

**Comment by lawlawlaw** [comment]
Fixed in pull request https://github.com/layer2tech/mercury-wallet/pull/1355
