### ISSUE TITLE
Coins recovered in "withdrawing" state remain in that state

### ISSUE THREAD

**Issue by lawlawlaw** [layer2tech/mercury-wallet#1364]
Coins in a recovered wallet remain in the withdrawing state even after a transaction has been included in a block.

**Comment by tomt1664** [comment]
Was this a coin that was withdrawn (init) before the wallet recovery?

**Comment by lawlawlaw** [comment]
> Was this a coin that was withdrawn (init) before the wallet recovery?

Correct - the wallet was recovered from seed before confirmation of the withdrawal transaction.
