### ISSUE TITLE
UI - Bullet points are using tor circuit css

### ISSUE THREAD

**Issue by rk16449** [layer2tech/mercury-wallet#1374]

**Comment by rk16449** [comment]
![bulletpoints2](https://user-images.githubusercontent.com/32778886/160117030-8f384dbe-7fa7-48c7-bf88-db5ccb5fb6e1.PNG)
![bulletpoints](https://user-images.githubusercontent.com/32778886/160117051-165b524a-88cf-43ca-a78e-721efe1f3be9.PNG)
![bulletpoints3](https://user-images.githubusercontent.com/32778886/160117066-2af57ca1-d758-42d0-9bd1-ef4c72a47096.PNG)

**Comment by lawlawlaw** [comment]
Fixed in v0.6.21.
