### ISSUE TITLE
In develop branch: received coin removed from coin list

### ISSUE THREAD

**Issue by lawlawlaw** [layer2tech/mercury-wallet#1379]
A coin received by transfer is removed from the coin list.
To recreate the bug:
1) Deposit a statecoin
2) While awaiting deposit confirmation, transfer a statecoin to the wallet from another wallet
3) Restart the wallet

The wallet confirms the newly deposited statecoin, but the transferred statecoin is no longer listed, and there is no information about the coin in the backup file.
All coins are recoverable from seed.

**Comment by tomt1664** [comment]
Thought I had a solution to this (saving the statecoin list after transfer finalize), but managed to see the same issue when testing it.

**Comment by lawlawlaw** [comment]
Ok - I'll look into it.

**Comment by lawlawlaw** [comment]
Fixed in v0.6.21.
