### ISSUE TITLE
Statecoin value wrong

### ISSUE THREAD

**Issue by nicosey** [layer2tech/mercury-wallet#1414]
![Screenshot 2022-04-18 at 11 52 27](https://user-images.githubusercontent.com/7435272/163798455-709fa7a5-96e1-4a8a-a79c-84ed95426e43.png)
 
Shows .5BTC

and is available for swap

https://mempool.space/address/bc1q570at5advs4fhewf5293hsc5v85l5mn0kvlqdk

**Comment by tomt1664** [comment]
90fadee...:2 is 0.5 BTC. 

A statecoin can only be a single output. Here, 2 x 0.5 are sent in 2 separate transactions.
