### ISSUE TITLE
Uncaught Error When Creating CPFP

### ISSUE THREAD

**Issue by sgershuny** [layer2tech/mercury-wallet#1493]
<img width="714" alt="image" src="https://user-images.githubusercontent.com/72019925/174269051-31d5bdf7-cc1e-4503-9d78-23d678177fcf.png">

**Comment by sgershuny** [comment]
> This coin was expired?

Yes coin has expired

**Comment by tomt1664** [comment]
Looking into the detail on this, it seems there must be some error in the fee calculation for the CPFP tx. The electrum server is returning 'min relay fee not met 109 < 110'. So the bitcoin node is calculating the fee as 110 sats, but we are calculating it as 109 sats. There must be some rounding error, or off-by-1 error is the tx size calculation.
