### ISSUE TITLE
Statechain not owned by this wallet error on withdrawal

### ISSUE THREAD

**Issue by tomt1664** [layer2tech/mercury-wallet#1514]
Wwithdrawal tx broadcast and was valid. 

(I believe) coin was then in 'withdrawing' status. User attempted to withdraw again, and claims they got the 'Statechain not owned by this wallet' error.

**Comment by tomt1664** [comment]
Error: DB Error: No data for identifier.

**Comment by Anatomist-Hookas** [comment]
Error: DB Error: No data for identifier.

Cannot withdraw my statecoins anymore. What can I do?

**Comment by sgershuny** [comment]
There are two options you have,

First go to Settings, click 'Manage Back-Up Transactions' then:

1) Click on the coin you wish to withdraw and you can get it's private key to import into your wallet

2) Create a CPFP transaction by setting a destination address and Fee rate, which will broadcast a transaction once the coin has expired. 

Otherwise, perhaps you are using an old version of the wallet with a bug.
In which case just download the latest version and try to withdraw.

**Comment by tomt1664** [comment]
> ```
> Error: DB Error: No data for identifier.
> ```
> 
> Cannot withdraw my statecoins anymore. What can I do?

Can you share some more info? What version wallet? Also, txid of coin and the identifier?

What were you doing to cause that error? Selected coin and clicked 'withdraw'?

**Comment by Anatomist-Hookas** [comment]
Well, I had the error before upgrading, then I upgraded to 0.7.8, same error.
Yes I selected the statecoin and then pressed withdraw, the confirm fee 0.5%, then the error.

**Comment by Anatomist-Hookas** [comment]
>     1. Click on the coin you wish to withdraw and you can get it's private key to import into your wallet

Which wallet? BTC core? Or Mercury itself, or any other wallet? If mercury, how?

**Comment by Anatomist-Hookas** [comment]
Also, there is an expired statecoin, if I try to withdraw this one, a different error shows up:

    Error: StateChain not owned by this Wallet. Incorrect proof key. Expected

**Comment by Anatomist-Hookas** [comment]
The non expired one, has 144 swaps, the expired one has 60 swaps.
No other statecoins in my wallet.

**Comment by tomt1664** [comment]
It seems you may need to perform a recovery from seed. Please wait for new release later on today (I'll link it here).

**Comment by Anatomist-Hookas** [comment]
I tried a recovery from seed, with a different wallet name, got this error:

    Error in Recovery - check online connection and retry

Looking forward to the next release.
