### ISSUE TITLE
Wallet won't open on large files

### ISSUE THREAD

**Issue by nicosey** [layer2tech/mercury-wallet#1617]
On latest release .17
If I leave the wallet running all day and large amounts of swaps done (over 2m wallet files)
The wallet locks up and I can't open the wallet at name/pwd stage.

**Comment by nicosey** [comment]
When I try to open same file with older wallet, there seems to be backward compatibility issue

**Comment by lawlawlaw** [comment]
In which version was the wallet created? Were the swaps done in version .17?
