### ISSUE TITLE
Swaps page swap groups information styling

### ISSUE THREAD

**Issue by 86667** [layer2tech/mercury-wallet#163]

**Comment by tomt1664** [comment]
Maybe we should wait for feedback from Tanel before starting this?

**Comment by tomt1664** [comment]
Swaps groups styling change from:

![Screenshot 2021-05-06 at 18 47 37](https://user-images.githubusercontent.com/15906918/117342852-97826080-ae9b-11eb-8ed6-81abf7839d0e.png)

to

![Screenshot 2021-05-06 at 18 42 14](https://user-images.githubusercontent.com/15906918/117342552-483c3000-ae9b-11eb-9bf3-1767ba4e8080.png)

https://www.figma.com/file/nJNKoVzdXOLZESBlIAocNV/Mercury-Wallet---UI?node-id=1%3A13047

Except: remove the 'Interval' column. 

Rename 'SWAP STATECOIN UTXO' button to 'JOIN GROUP'
Rename 'REMOVE STATECOIN UTXO FROM SWAP' to 'LEAVE GROUP'

Place both of these buttons next to each other in the same row at the bottom of the swap groups.
