### ISSUE TITLE
Swap stuck in phase 6/8 - how can I fix?

### ISSUE THREAD

**Issue by Privatize0635** [layer2tech/mercury-wallet#1646]

**Comment by tomt1664** [comment]
Swaps that do not complete within specified time-out period (a few minutes) should automatically cancel and revert. Is that happening here? If it's remaining stuck for an extended period, then this is a bug. 

Or, is it reverting correctly but the same coin keeps getting stuck at the same phase, again and again?

Please provide some more info.

**Comment by Privatize0635** [comment]
-In this case, the swap has been stuck in phase 6/8 for several days - not automatically cancelling/reverting. It's remaining stuck.
-Have tried toggling auto-swap on/off on swap screen but does not change the status of being stuck in phase 6/8.
-Swaps of the same denomination are running at the same time with no problems.

**Comment by tomt1664** [comment]
OK, thanks. Looking into it and will get back to you ASAP. In the meantime, if you have access to the dev tools (if you are on mac, to the top menu bar, click on 'View' and then 'Toggle developer tools') and see if there is any output in the console.

**Comment by tomt1664** [comment]
Please try the new release if you are still having the issue. https://github.com/layer2tech/mercury-wallet/releases/tag/v0.7.23

**Comment by Privatize0635** [comment]
Yes, the new release fixes it. Thank you and keep it up! Great project.
