### ISSUE TITLE
Awaiting Confirmations, 537 out of 3 Confirmations and Counting

### ISSUE THREAD

**Issue by ThroatHugs** [layer2tech/mercury-wallet#2106]
I'm now running into an issue where I can't transfer or withdraw my statecoins. Whenever I attempt to transfer, swap, or withdraw my statecoins I'm prompted with:

Coin unavailable for swap - awaiting confirmations

This is despite the number of confirmations being listed as 537 out of 3, along with the transaction being confirmed on the blockchain. The link to the transaction is provided provided below and supporting screenshots are attached.

https://blockchair.com/bitcoin/transaction/5b0bbd7a0dfca6b1961139e9716d9eb9597d3bd3f06bea29203c4037a0662095?from=bitcoin.com

<img width="1192" alt="Screen Shot 2023-10-03 at 3 18 01 AM" src="https://github.com/layer2tech/mercury-wallet/assets/146473695/ac209780-591a-44ef-aa47-c373acca0d8d">
<img width="374" alt="Screen Shot 2023-10-03 at 3 18 22 AM" src="https://github.com/layer2tech/mercury-wallet/assets/146473695/ee717f3e-916f-4748-8690-0791a95d207e">
<img width="1179" alt="Screen Shot 2023-10-03 at 3 20 17 AM" src="https://github.com/layer2tech/mercury-wallet/assets/146473695/ca4c75bb-b981-43a7-8534-0034fc6eb0d6">

**Comment by tomt1664** [comment]
Presuming this was a coin recently deposited. Did you send a different amount to the one selected? That should be fine and the wallet can handle that, but it looks like its got stuck in a state where it is not finishing the deposit confirm process. There are a couple of options: I think I know what is causing it, and we can update the app (will take a day or two) or you can try manually modifying the wallet file. 

What platform are you using? On e.g. mac, the wallet data is in `/Users/username/Library/Application Support/mercurywallet/wallets/` in a directory `wallet_name/config.json`. In this file there is a list of coins under `statecoins_obj`. For that coin, there is a key `"backup_confirm": true`. If you change this from `true` to `false` and then re-open the wallet, it should finalise the deposit process.

**Comment by ThroatHugs** [comment]
Thank you for getting back to me so soon, I'm on mac and the bitcoin was
deposited into the wallet 5 days ago on the 29th. I tried modifying the
wallet data folder like you said, first for just the original wallet and
then both the original wallet as well as its back up (both of which are on
this computer) but it doesn't seem to have done anything and when I check
the files after opening mercury wallet the backup_confirm is reverted to
true

**Comment by ThroatHugs** [comment]
Great, thank you so much for your help!

**Comment by tomt1664** [comment]
Hi - an updated version of the wallet is here: https://github.com/layer2tech/mercury-wallet/releases/tag/v0.9.1

Try - if it still is stuck, could you go to the menu bar View -> Toggle developer tools, and see if there is anything in the console.

**Comment by ThroatHugs** [comment]
**Issue persists after loading wallet in 0.9.1, here are my steps (all done on mac):** 

1. Downloaded the mac.zip of 0.9.1 and loaded wallet, same issue 

3. Decided to delete other versions of mercury wallet and the mercury wallet folder from my mac, (saved backups elsewhere)

5. Downloaded the .dmg of 0.9.1 and restored wallet using seed, same issue

6. Quit mercury wallet and went to the config.json in "/Users/username/Library/Application Support/mercurywallet/wallets/wallet_name"

7. There are two portions where "statecoins_obj" appears one with version 0.9.1 and another for 0.9.0 and so two "backup_confirm: true" Edited the first "backup_confirm: true" to "backup_confirm: false" (the one under version 0.9.1)

8. Opened mercury wallet and when trying to load the wallet I was met with the error: Invalid wallet - TypeError: Cannot read properties of undefined (reading 'bech32')

9. I ran into this issue in 0.9.0 and resolved it by downloading 0.8.14 and loading my wallet there, which then let me load my wallet successfully in 0.9.0

10. I wanted to avoid downloading a release other than 0.9.1 for the sake of consistency and so I restored my wallet via its backup file (made in 0.9.0)

11. The wallet backup loaded successfully, but issue with the confirmation persisted

12. Quit mercury wallet and went to the config.json in "/Users/username/Library/Application Support/mercurywallet/wallets/wallet_name_backup"

13. Again there were two portions with "statecoins_obj" just like before

14. Edited the first "backup_confirm: true" to "backup_confirm: false" (the one under version 0.9.1)

15. Loaded wallet backup successfully

16. A few seconds later the window went blank white and the application was named index.html, console was repeating something along the lines of "connection error"

17. Quit mercury wallet and edited the config.json in the backup wallet folder, this time both "back_confirm: true" to 
"back_confirm: false" 

18. Loaded wallet backup successfully 

19. Again,  a few seconds later the window went blank white and the application was named index.html, console was repeating something along the lines of "connection error"

20. Quit mercury wallet and edited the config.json in the backup wallet folder, this time only the second "back_confirm: true" to "back_confirm: false" (under version 0.9.0)

21. Loaded wallet backup successfully 

22. Application didn't blank and operated normally, but confirmation issue persisted

23. Repeated steps 11-14, but this time application didn't blank and operated normally, but confirmation issue persisted

24. Repeated steps 16-17, but again this time application didn't blank and operated normally, confirmation issue persisted


Afterwards, I quit the application and loaded the backup wallet again and checked the console. I noticed this error repeating:

Uncaught (in promise) Error: SharedLibError Error: Format Error: Incorrect State Entity fee - expected 8398, got 8399
    at Nt (error.ts:21:11)
    at http_client.ts:138:9

I can post the console log if necessary (not sure if it could contain any sensitive personal info, in that case I can send it privately)

**Comment by tomt1664** [comment]
OK thanks for this - the error seems to be some kind of edge case or rounding error in the fee calculation 8398 vs 8399 (probably not seen before due to the odd value). I'll update the server side and let you know when done (later today hopefully). 

Sorry for the hassle.

**Comment by ThroatHugs** [comment]
Thanks a lot, you’ve been a great help - looking forward to it

**Comment by ThroatHugs** [comment]
Hey, just wanted to inquire if there've been any updates with the server
issue?

Thanks in advance.
