### ISSUE TITLE
Infinite number of statecoin utxos after sending wrong amount of tBTC to deposit address

### ISSUE THREAD

**Issue by urza** [layer2tech/mercury-wallet#265]
Basically the title says it. I wanted to test Mercury Wallet on testnet. I tried to create new statecoin, but the testnet faucet didn't asked me for the amount and just sent some random value to the address. See screenshot for happened in wallet. The list continues down and new duplicate items are still being created.

![image](https://user-images.githubusercontent.com/189804/115971676-0978b280-a54a-11eb-9d2f-5da2567dc6eb.png)

**Comment by 86667** [comment]
@urza Thanks for feedback, this should have been fixed in version 0.2. Are you using a previous version?

**Comment by urza** [comment]
@86667 I believe I was using 0.2.12 - the last with linux binary (the very last doesnt have linux binary)
