### ISSUE TITLE
Swap group status labels

### ISSUE THREAD

**Issue by tomt1664** [layer2tech/mercury-wallet#354]
In the 'swaps waiting to begin' box, for each entry:

If the group is empty (i.e. 0/X), then the text in the shape should be 'Empty' and the colour of the shape as it is currently (grey). 

If there are 1 or more (but not full or nearly full, i.e. X-1/X), the text should be 'Awaiting' and the colour #dfeaff (light blue)

If there are X-1/X the text should be 'Pending' and the color #c8e6c9 (light green)

If it is X/X the text should be 'Complete' and the colour #ffccbc (light orange)
![Screenshot 2021-05-28 at 14 22 28](https://user-images.githubusercontent.com/15906918/119993328-5a554e00-bfc3-11eb-8822-0c85271abcf8.png)

**Comment by alexyjs** [comment]
@tomt1664 
> If there are 1 or more (but not full or nearly full, i.e. X-1/X), the text should be 'Awaiting' and the colour #dfeaff (light blue)
> If there are X-1/X the text should be 'Pending' and the color #c8e6c9 (light green)

Please clarify these cases. I guess the text is ‘Awaiting’ when (total - actual > 1), and ‘Pending' (total - actual == 1)?
Also the text look blurred with the grey background, please clarify the background of those statuses as well.

**Comment by tomt1664** [comment]
So with (actual/total), then yes ‘Awaiting’ when (total - actual > 1), and ‘Pending' (total - actual == 1). 

When empty, the background colour should be #f5f5f5
