### ISSUE TITLE
Statecoin amount highlighted but not selected on deposit page 

### ISSUE THREAD

**Issue by lawlawlaw** [layer2tech/mercury-wallet#363]
When you enter the deposit page, a statecoin amount highlighted in the GUI is not actually used to initiate a deposit. To replicate:

1. Click deposit
2. Click a statecoin value
3. Click continue
4. Complete deposit then click go back
5. The same statecoin value is still highlighted. Click continue without clicking anything else first. The deposit fails to inititate.

**Comment by tomt1664** [comment]
Not sure this is a function bug, more of a UI bug. The correct behaviour should be that the user selects the coin, and then clicks join and joins a group with the min swap group number. The groups list should have nothing selectable, and is there for information only.
