### ISSUE TITLE
Deposit custom amount

### ISSUE THREAD

**Issue by tomt1664** [layer2tech/mercury-wallet#388]
![Screenshot 2021-06-09 at 08 57 11](https://user-images.githubusercontent.com/15906918/121315988-c491bb00-c900-11eb-9cb8-9b582ee89ade.png)

The bottom right deposit value replaced with this option. Clicking on this element opens a box where the user can type a number for the deposit amount.

**Comment by tomt1664** [comment]
When the 'Other' option is clicked on, a text box appears which allows the user to enter a number. When 'enter' is hit, that deposit amount replaces the 'Other' text and is selected.

**Comment by rk16449** [comment]
merged/fixed into develop
