### ISSUE TITLE
Error when depositing small values

### ISSUE THREAD

**Issue by rk16449** [layer2tech/mercury-wallet#395]
Sometimes when I deposit the smaller values such as 0.00001 BTC I get this error (not all the time, have to debug further)
![08 06 2021-bug](https://user-images.githubusercontent.com/32778886/121565843-c5b40c80-ca14-11eb-85df-8f156e0cd512.jpg)

This then makes the wallet unusable as the same message keeps coming up constantly -I have to keep crossing it out. Current solution is to create a new wallet.
![0_trim](https://user-images.githubusercontent.com/32778886/121566058-090e7b00-ca15-11eb-8af8-e07ea861c8b8.jpg)

**Comment by tomt1664** [comment]
https://github.com/layer2tech/mercury-wallet/issues/65
