### ISSUE TITLE
Handle transfer change/failure

### ISSUE THREAD

**Issue by tomt1664** [layer2tech/mercury-wallet#40]
Handle the situation when transfer sender is not completed. 

1. If the transfer message is lost, the sender should be able to view/copy it again from somewhere. 
2. If the receiver does not claim, can the sender recover the coin (either to withdraw or send to someone else). 

Handling this cleanly may require changes to the logic in mercury-server.

**Comment by 86667** [comment]
Wallet:
- Store `TransferMsg3`'s with StateCoin
- Add `spend_pending` to StateCoin and mark true
- Periodically poll Server for all initilised spends asking if `transfer_receiver` has been perfromed yet - if so set `spent=true`
- Continue to show `spend_pending` coins in GUI Coins list and display `TransferMsg3` in info when clicked. Allow coin to be spent elsewhere at any time. (perhaps with a warning if `transfer_sender` has been performed?

Server:
- API to check if statechains have changed ownership

**Comment by tomt1664** [comment]
Transfer message now available from coinslist.
