### ISSUE TITLE
Not enough value to cover fee

### ISSUE THREAD

**Issue by lawlawlaw** [layer2tech/mercury-wallet#433]
After depositing a statecoin the following error occurs:
![Screenshot from 2021-06-18 09-30-14](https://user-images.githubusercontent.com/4256700/122532771-c5b99b00-d018-11eb-8fba-55c8a372be47.png)

**Comment by rk16449** [comment]
Looking at the console, it seems the value entered was 10 satoshi, fee is around 300 satoshi. Deposit screen should have filtered values below this. Which amount did you select to deposit?

**Comment by tomt1664** [comment]
Which version of the code are you using? Should be prevented by this https://github.com/layer2tech/mercury-wallet/pull/425 in the latest release (0.2.31).
