### ISSUE TITLE
ERR_FILE_NOT_FOUND issue on start up

### ISSUE THREAD

**Issue by nicosey** [layer2tech/mercury-wallet#436]
![Screenshot 2021-06-18 at 19 45 04](https://user-images.githubusercontent.com/7435272/122604342-b7499e80-d06d-11eb-997c-5da43fdd18ac.png)

**Comment by tomt1664** [comment]
This is the fonts ('Roboto') files. Font looks fine in the GUI - we should check it is not getting them from somewhere else (public) as this would be a privacy issue.
