### ISSUE TITLE
Activity list created Statecoin before BTC deposit

### ISSUE THREAD

**Issue by sgershuny** [layer2tech/mercury-wallet#443]
<img width="764" alt="Screenshot 2021-06-22 at 10 01 04" src="https://user-images.githubusercontent.com/72019925/122896394-f105f800-d340-11eb-94d0-5baf88766207.png">

Activity lists a Statecoin as created before bitcoin deposited in account.

The created Statecoin appears after you click to generate a shared key not once any BTC has actually been sent.

Activity should only list this in activity once the bitcoin deposit has been made.

**Comment by nicosey** [comment]
Per user feedback it would be better to keep the Activity tab the same, however add under the statecoins an empty entry that shows the statecoin has not been deposited.  

Key thing is we don't want users to mistakenly to create lots of statecoin addresses.
