### ISSUE TITLE
Unconfirmed coins disappear on wallet load from seed

### ISSUE THREAD

**Issue by sgershuny** [layer2tech/mercury-wallet#453]
Coins deposited and remain in Mempool:

<img width="1001" alt="Screenshot 2021-06-23 at 09 30 50" src="https://user-images.githubusercontent.com/72019925/123064068-dba6d180-d405-11eb-99a8-138acd6666b6.png">

When loading the wallet from seed, it says no coins in account and comes up with this error:

<img width="1051" alt="Screenshot 2021-06-22 at 21 57 43" src="https://user-images.githubusercontent.com/72019925/123064195-f711dc80-d405-11eb-9a15-b70081f1232d.png">

**Comment by tomt1664** [comment]
Recovery API change conflict

**Comment by tomt1664** [comment]
Not being caused by changes to the server API response.

**Comment by tomt1664** [comment]
It is due to the recovery function requiring master key data, which is stored in the lockbox when it is active. 

https://github.com/commerceblock/mercury/issues/206
