### ISSUE TITLE
Wallet names with "." not saved with full name

### ISSUE THREAD

**Issue by sgershuny** [layer2tech/mercury-wallet#454]
Any wallet name created with a "." in it has its name cropped on save.

e.g.
<img width="401" alt="Screenshot 2021-06-23 at 12 09 12" src="https://user-images.githubusercontent.com/72019925/123087084-0e5bc480-d41c-11eb-8e31-d192ab892d33.png">

This wallet was saved as: "walletTest123.2" the ".2" was cropped.

Solution: when creating wallets the wallet name shouldn't be allowed to contain certain characters that could affect the code or how the wallet is saved.

**Comment by tomt1664** [comment]
We should also prevent people using /
