### ISSUE TITLE
Coin Info modal bug

### ISSUE THREAD

**Issue by nicosey** [layer2tech/mercury-wallet#473]
Coin Info modal in dark mode does not show Close button.
![Screenshot 2021-06-25 at 10 35 50](https://user-images.githubusercontent.com/7435272/123404808-2446c200-d5a1-11eb-8107-477238f20182.png)

**Comment by nicosey** [comment]
Also on settings

**Comment by nicosey** [comment]
<img width="1157" alt="Screenshot 2021-06-25 at 22 35 41" src="https://user-images.githubusercontent.com/7435272/123487483-e0d26f00-d605-11eb-9d65-e8e1b73da533.png">

**Comment by rk16449** [comment]
Not able to replicate on my end, wallet shows the buttons for me
