### ISSUE TITLE
Statecoin deposit options disappear when scrolling

### ISSUE THREAD

**Issue by cbjd** [layer2tech/mercury-wallet#513]
This happens in dark and light mode on OSX Catalina 10.15.7 Scrolling down then up causes the first line of statecoin denominations to disappear

https://user-images.githubusercontent.com/86799822/124182853-6bdbbb00-da85-11eb-9987-f38629e5fe88.mov

**Comment by tomt1664** [comment]
What happens here is that default values are shown while waiting for the server to respond with liquidity info, when only deposit values with liquidity are shown. Usually takes 1-2 seconds. 

We are going to not show the default values and have the screen blank until the liquidity info is returned. https://github.com/layer2tech/mercury-wallet/issues/442
