### ISSUE TITLE
"Error: Error: Backup tx locktime not correctly decremented" when attempting a self-send

### ISSUE THREAD

**Issue by cbjd** [layer2tech/mercury-wallet#527]
Mercury 0.3.1, OS X 10.15.7

Steps taken:
1) Generate new wallet
2) Deposit statecoin
3) Press RECEIVE button
4) Generate address
5) Go back
6) Press SEND button
7) Copy in receive address
8) Select statecoin
9) Press Send Statecoin UTXO button
10) This error was thrown: "Error: Error: Backup tx locktime not correctly decremented" -- statecoin was never received by wallet

txid: 
80a2da949042d3c1d364bc67f90f2d4bc8b29e5499e14ee3009f99a25929f329

Address was one of these two: 
sc1qgnrmfmr679jaxexg6vh5xmqwj37s7m3rx7j3w682fzygvpazrcxxc92g9v
sc1qdlhu6zthp5n9e6fha4xu2danc4h2enav07q5tw6pkyu3ety62ha74hu7rh

One thing I did notice, is that when I first deposited the statecoin it showed an expiration of 3 months, then at some point before the transfer it had gone down to 2 months. Not sure if that is helpful.

<img width="808" alt="Screen Shot 2021-07-05 at 10 11 24 AM" src="https://user-images.githubusercontent.com/86799822/124487724-0fc2b080-dd7d-11eb-99d2-f81b44823aec.png">

**Comment by tomt1664** [comment]
https://github.com/commerceblock/mercury/issues/212

and 

https://github.com/layer2tech/mercury-wallet/issues/553
