### ISSUE TITLE
Dependency Issue

### ISSUE THREAD

**Issue by rk16449** [layer2tech/mercury-wallet#530]
Steps:
1. Fresh git clone of mercury-wallet
2. Checkout to latest develop branch
3. Run npm install inside mercury-wallet
4. Cannot install due to dependency error
![dependency issue](https://user-images.githubusercontent.com/32778886/124497130-54b50a00-ddb2-11eb-8a29-dcbded52d8d6.PNG)

**Comment by sgershuny** [comment]
what about when you run 'yarn app-macos' ?

**Comment by rk16449** [comment]
Was having this issue on linux, moved over to mac os - npm install works correctly
