### ISSUE TITLE
Error raised on refresh 'Receive' page 

### ISSUE THREAD

**Issue by sgershuny** [layer2tech/mercury-wallet#535]
When the Receive page is refreshed this error appears:

<img width="910" alt="Screenshot 2021-07-06 at 11 17 39" src="https://user-images.githubusercontent.com/72019925/124584267-f2104c80-de4b-11eb-8196-dae0903a714c.png">

**Comment by tomt1664** [comment]
Is this is `yarn run dev` mode with a re-run? It seems to be saying `wallet` is undefined.

**Comment by sgershuny** [comment]
Yes I think it's trying to render the page after wallet is unloaded and account logged out, I'm adding in error handling for it now
