### ISSUE TITLE
Delete wallet feature

### ISSUE THREAD

**Issue by rk16449** [layer2tech/mercury-wallet#555]
There seems to not be a way to delete your wallet from memory, and as a result per the new version we have an accumulation of old wallets

**Comment by tomt1664** [comment]
Simplest solution is to enable users to delete wallets manually via the filesystem. In order to do this, each wallet should be stored as separate files, instead of as one single file.

**Comment by tomt1664** [comment]
So instead of a single `config.json` a separate file for each saved wallet instance.
