### ISSUE TITLE
Cannot read property setBlockHeight of undefined

### ISSUE THREAD

**Issue by sgershuny** [layer2tech/mercury-wallet#562]
The error below has appeared in the following cases: 
- Creating a new wallet, after wallet name and password entered.
- Logging out and logging back into a wallet in quick succession

<img width="881" alt="Screenshot 2021-07-12 at 09 49 00" src="https://user-images.githubusercontent.com/72019925/125258713-853afd80-e2f6-11eb-9ec2-b29970c126ec.png">
<img width="311" alt="Screenshot 2021-07-12 at 09 49 08" src="https://user-images.githubusercontent.com/72019925/125258727-8835ee00-e2f6-11eb-9d41-56e266c57fa8.png">

**Comment by sgershuny** [comment]
This Error occurs when funding is found but no wallet is loaded.

**Comment by rk16449** [comment]
fixed with
`function setBlockHeightCallBack(item) {
  if(wallet) {
    wallet.setBlockHeight(item);
  }
}`
