### ISSUE TITLE
Withdraw coins after swap

### ISSUE THREAD

**Issue by sgershuny** [layer2tech/mercury-wallet#573]
Error appears: Incorrect proof key. Even though swap appears to complete.

<img width="583" alt="Screenshot 2021-07-13 at 19 50 10" src="https://user-images.githubusercontent.com/72019925/125586935-9c2d1899-6a8b-4041-89d0-b1fc38e73226.png">

**Comment by tomt1664** [comment]
Same cause as this:

https://github.com/layer2tech/mercury-wallet/issues/659
