### ISSUE TITLE
Leaving wallet in swap

### ISSUE THREAD

**Issue by rk16449** [layer2tech/mercury-wallet#623]
Unusual behaviour on swaps when leaving the wallet.

1. Join a swap - phase 0
2. Leave the wallet
3. Reload wallet from memory
4. See swap at phase 0 again
5. go to swaps page
6. swaps are now reset
7. go to main page, swaps also reset

**Comment by tomt1664** [comment]
Wallet to drop out of all swaps and registrations if the wallet is closed/exited.
