### ISSUE TITLE
Dark mode improvements

### ISSUE THREAD

**Issue by tomt1664** [layer2tech/mercury-wallet#636]
In dark mode, some button text is not visible:

In settings:

![Screenshot 2021-07-27 at 14 23 24](https://user-images.githubusercontent.com/15906918/127667410-369ea467-95af-4f28-97b5-bf425c29c603.png)

In the coin info modal:

![Screenshot 2021-07-27 at 14 23 44](https://user-images.githubusercontent.com/15906918/127667499-3e17c73e-3e1f-449b-b850-21137ee6457c.png)

The buttons with a white background look too bright - better with white text on a dark background:

![Screenshot 2021-07-27 at 14 24 21](https://user-images.githubusercontent.com/15906918/127667629-323f92d9-6199-4a12-95a1-375e3a11c1d2.png)

![Screenshot 2021-07-27 at 14 24 46](https://user-images.githubusercontent.com/15906918/127667643-8a89d49b-4878-45b7-b4ab-d4ce1c341077.png)

**Comment by tomt1664** [comment]
![Screenshot 2021-08-10 at 08 57 35](https://user-images.githubusercontent.com/15906918/128830279-47c963ab-36fc-4847-97a9-1ba1a5d44ae6.png)

**Comment by rk16449** [comment]
There are still known issues with:

1. coin info modal
2. state coin address to send to
3. pressing on create wallet backup

**Comment by rk16449** [comment]
Fixed all known issues
