### ISSUE TITLE
Auto-swap feature. 

### ISSUE THREAD

**Issue by tomt1664** [layer2tech/mercury-wallet#672]
Option (switch) when performing 'join group' that puts the coin in an auto-swap status (i.e. it automatically rejoins the group after leaving (for either completion or failure). 

This switch (checkbox or switch) can be placed next to the join group button. 

'Leave group' cancels the autoswap.

**Comment by tomt1664** [comment]
https://github.com/layer2tech/mercury-wallet/tree/autoswap

**Comment by rk16449** [comment]
Known bug - When a swap fails,  the auto  swap toggle   is still enabled, which looks like to the user that it is still on - the auto swap does not reconnect with swaps - looking into fixing it
