### ISSUE TITLE
Login throws error after logging out during a swap

### ISSUE THREAD

**Issue by sgershuny** [layer2tech/mercury-wallet#675]
I couldn't login to my account when I logged out during swap with error below shown:

<img width="991" alt="Screenshot 2021-08-23 at 17 47 27" src="https://user-images.githubusercontent.com/72019925/130486869-9aa9248e-50a9-4140-ac06-75e80647c933.png">

I entered 3 coins into a swap, when the timer reached 0s the swap started. When the coins reached swap phase 4, I logged out of my account. I could then not log in again as this above error showed whenever I clicked 'continue'.

**Comment by rk16449** [comment]
#643
