### ISSUE TITLE
Connection error when registering for swap

### ISSUE THREAD

**Issue by tomt1664** [layer2tech/mercury-wallet#764]
All other wallet operations seem fine, but get following error when registering coin for swap (either clicking autoswap or join group). 

![Screenshot 2021-09-22 at 15 08 17](https://user-images.githubusercontent.com/15906918/134361081-7046eb79-3f3c-43d2-bce4-ba53b6dece6f.png)

![Screenshot 2021-09-22 at 15 08 26](https://user-images.githubusercontent.com/15906918/134361104-0ae0b8a1-0439-4c0a-8276-2cdfd62cf222.png)

![Screenshot 2021-09-22 at 15 09 02](https://user-images.githubusercontent.com/15906918/134361138-b56edbf9-f870-44c8-ad24-b329beac5ea9.png)

**Comment by lawlawlaw** [comment]
Fixed in https://github.com/layer2tech/mercury-wallet/pull/756
