### ISSUE TITLE
Bug: not showing value on transfer

### ISSUE THREAD

**Issue by nicosey** [layer2tech/mercury-wallet#809]
<img width="1130" alt="Screenshot 2021-10-28 at 20 44 30" src="https://user-images.githubusercontent.com/7435272/139324800-9d4e40fe-19aa-4845-b243-0072a918ce17.png"
<img width="1053" alt="Screenshot 2021-10-28 at 20 44 46" src="https://user-images.githubusercontent.com/7435272/139324816-04a703ad-72fd-4376-a11d-ca7a3126a610.png">
>

**Comment by tomt1664** [comment]
Fixed
