### ISSUE TITLE
Adaptor shutting down when machine sleeps?

### ISSUE THREAD

**Issue by tomt1664** [layer2tech/mercury-wallet#860]

**Comment by sgershuny** [comment]
On the Mac there are two sleep settings: one is display and more graphical sleep the other is a deeper sleep. Lighter sleep is called 'Battery' energy saver and the deeper is 'Power Adapter'.

When the computer enters deeper sleep thats when the connection issues happen. Initially the wallet loads swap but has troubles joining swap. Wallet can't load deposit page either.

Keeping wallet alive for another two minutes and connection comes back.
