### ISSUE TITLE
Received own statecoin back in swap, no warning

### ISSUE THREAD

**Issue by cbjd** [layer2tech/mercury-wallet#879]
I did a two party swap in the .001 swap pool and received back my own coin. There was no warning or indication that this happened, and my privacy score was specified as "2."

The coin I was using to swap was received from an earlier swap, and it is possible that the other coin in the swap pool was the original coin I had swapped for (unclear, but just an educated guess given low liquidity). Not sure if that matters.

Full history:
Deposited Coin X.
Swapped for Coin Y
Did a self-send of Coin Y in the same wallet.
Entered Swap with Coin Y, received Coin Y again.

Statecoin address (Coin Y): sc1qvu4ushhwh5mtpgsgk8egh9zn8fmenhpw93prwkzjchex8nkpzzn7wdc3wc

**Comment by lawlawlaw** [comment]
We will apply the following changes to help clarify the coin status after swap:
- The text "Swap set: X" and "privacy score: X" will be replaced with "Swap count: Y" where Y is simply the number of swaps completed.
- The indicator privacy indicator will turn orange only if the coin was received in a swap and is not a coin that was originally deposited in the wallet.
- The text "Swap count: Y" will be replaced with "Coin originally deposited in this wallet" or similar if the coin was originally deposited in the wallet.
- There already exists a cross/tick symbol below the coin value indicating whether the coin was originally deposited in the wallet. We will add a description explaining this to the tool tip.
- We will add a pop up message alerting the user if the same coin was received in a swap and/or a coin originally deposited in the wallet was received in a swap.
