### ISSUE TITLE
Auto-Swap but coin not in swap pool

### ISSUE THREAD

**Issue by nicosey** [layer2tech/mercury-wallet#880]
See image

![Screenshot 2021-11-14 at 18 24 18](https://user-images.githubusercontent.com/7435272/141693657-caed4f2c-d98c-4f27-a99f-36eac202a459.png)

**Comment by nicosey** [comment]
Not sure if this is related to about bug.
But after being a swap with no participants, the autoswap failed

**Comment by nicosey** [comment]
Actually it does seem autoswap is broken and I just completed a swap and autoswap switched off

**Comment by nicosey** [comment]
<img width="1134" alt="Screenshot 2021-11-14 at 21 17 37" src="https://user-images.githubusercontent.com/7435272/141698976-530764ba-1c4e-45cb-a360-bb5de4a47e66.png">

**Comment by cbjd** [comment]
> Actually it does seem autoswap is broken and I just completed a swap and autoswap switched off

I experienced this as well. At least when a swap fails auto-swap is being disabled.
