### ISSUE TITLE
Coin stuck in Phase 0

### ISSUE THREAD

**Issue by nicosey** [layer2tech/mercury-wallet#881]
This seem UI error and it has not updated from previous swap

Its actually participating in new swap, but it still says stuck in Phase 0.

![Screenshot 2021-11-14 at 18 45 39](https://user-images.githubusercontent.com/7435272/141694330-b0f13836-d516-493a-bfe8-94b67d22ed62.png)

**Comment by rk16449** [comment]
Unable to reproduce
