### ISSUE TITLE
Activity log does not show history of inbound statecoins transfers

### ISSUE THREAD

**Issue by cbjd** [layer2tech/mercury-wallet#899]
In the Activity log I see when coins are initialized/created, swapped and transferred out of the wallet, but when a statecoin is transferred to my wallet I do not see it in the activity log. Is there a specific reason for that?

**Comment by tomt1664** [comment]
Not really. Obviously in a swap (where you do send and receive in a single operation) you only want to record one event. 
We'll add an entry to the activity list when receiving a coin directly.
