### ISSUE TITLE
In Dark Mode, Activity log difficult to read when surfacing extra details about swaps

### ISSUE THREAD

**Issue by cbjd** [layer2tech/mercury-wallet#902]
When you hover over a swap where it surfaces the "Swap TXID" and the "New TXID" the font is white, and the overlay is gray, so you can't quite read what is there.
<img width="357" alt="Screen Shot 2021-11-17 at 2 07 53 PM" src="https://user-images.githubusercontent.com/86799822/142266391-bf3a4a72-50c6-4b7e-a2c6-334b06e3c62c.png">

**Comment by rk16449** [comment]
Added a fix for dark mode in the next release

**Comment by cbjd** [comment]
@rk16449 FYI I just noticed this also occurs when using the show Private Key WIF button.

**Comment by rk16449** [comment]
@cbjd thanks, added this fix for todays release
