### ISSUE TITLE
Statecoin was transferred out of wallet, but still shows as available

### ISSUE THREAD

**Issue by cbjd** [layer2tech/mercury-wallet#903]
Wallet is fully synced to current block height.

The statecoin is displayed as available for transfer and swap in the UI, but expectedly fails when attempting to swap: 

```
SharedLibError Error: Error: secp: signature failed verification
```

on transfer:

```
Error: StateChain not owned by this Wallet. Incorrect proof key: REDACTED
```

Statecoin address: sc1qgvqes569uu3gp9j2n38hzzy6rway804avjf2qmtx4g6kv2wv9zzv2q6hz9

Mercury 0.4.51
OS X 10.15.7

**Comment by tomt1664** [comment]
Looking into this. Can you confirm that this was a direct transfer (to another wallet, or the same wallet?)? Also that the coin was transferred successfully to the destination? Thanks.

**Comment by tomt1664** [comment]
OK, thanks. If you can remember: were you able to receive the coin to the other wallet using the 'Receive index: x' process, or did you use/have to use the transfer key?

**Comment by cbjd** [comment]
Yes I used the Receive Index button.

**Comment by cbjd** [comment]
@tomt1664 I have another instance of this, however this time it occurred after a swap.

Statecoin address: sc1qggmz8z6qz7l66g9yzdzkeqmtm9y2ly8s73l057elrvzfk5nud6k5yt7xdr

**Comment by tomt1664** [comment]
So you received a new coin (in the swap) but the one you swapped (which was sent to the other party in the swap) remained in the wallet (but unspendable - i.e. gave an error of `Error: StateChain not owned by this Wallet. Incorrect proof key` if you tried to send it?

**Comment by cbjd** [comment]
Yes that is what occurred.

**Comment by tomt1664** [comment]
Should have been fixed in https://github.com/layer2tech/mercury-wallet/pull/975
