### ISSUE TITLE
Connected to Server + Bitcoin (Electrum) but not swaps

### ISSUE THREAD

**Issue by nicosey** [layer2tech/mercury-wallet#908]
![Screenshot 2021-11-19 at 15 32 18](https://user-images.githubusercontent.com/7435272/142648869-a25434ae-45ad-4707-8902-e735f97b3121.png)

**Comment by rk16449** [comment]
cannot reproduce / debug issue, this could be due to the user on old wallet/wrong connection info or the server is down

**Comment by rk16449** [comment]
this could be due to the user on old wallet/wrong connection info or the server is down

**Comment by rk16449** [comment]
viewing the css when this occurs, ::after is not being applied to this span - may not be a connection issue but a visual bug
