### ISSUE TITLE
Same coin appears twice after Swap

### ISSUE THREAD

**Issue by nicosey** [layer2tech/mercury-wallet#911]
<img width="1139" alt="Screenshot 2021-11-19 at 21 18 57" src="https://user-images.githubusercontent.com/7435272/142693018-43b5b31b-6584-4f91-a6c2-04060ca3653d.png">

See image above, i have the same coin displayed twice
The was in new release 0.4.52

**Comment by cbjd** [comment]
Possibly related: https://github.com/layer2tech/mercury-wallet/issues/903#issuecomment-974493101
