### ISSUE TITLE
Withdrawing a statecoin below the minimum statecoin size results in a transaction with dust output

### ISSUE THREAD

**Issue by cbjd** [layer2tech/mercury-wallet#917]
When you deposit a statecoin below the minimum threshold size, a warning is displayed in Statecoin list, indicating that the statecoin is too small to be withdrawn on its own, and must be combined in a "batch" withdrawal with another coin.

If you ignore this warning and attempt to withdraw the coin, a raw transaction is produced with the following error: 

```
Error: Transaction broadcast failed with error: Error: 400 - "sendrawtransaction RPC error: {\"code\":-26,\"message\":\"dust\"}" after 10 attempts. See the withdrawnn statecoins list for the raw transaction.
```

On inspection of the raw transaction, it looks like the fee output for Mercury is below the dust threshold. 

Might be best to restrict selecting these small coins for withdrawal by themselves to avoid this error being exposed in the client.

**Comment by tomt1664** [comment]
Do not allow a withdrawal tx with total input < 0.001 BTC.
