### ISSUE TITLE
Prevent Error in Deposit Backup

### ISSUE THREAD

**Issue by sgershuny** [layer2tech/mercury-wallet#968]
It is possible to make a deposit when the block height has not been set.

Connection looks like this:

![image](https://user-images.githubusercontent.com/72019925/144474132-a5342128-9e2a-4ef3-8771-760998cf0b54.png)

This causes coins to have 0 Expiry Time

![image](https://user-images.githubusercontent.com/72019925/144474242-a04445fd-adcd-4567-a3fa-6a7903dbc218.png)

**Comment by tomt1664** [comment]
Can you post the backup tx (if you have it)? 

Did you try restarting the wallet?
