### ISSUE TITLE
Wallet stuck with connection issues

### ISSUE THREAD

**Issue by nicosey** [layer2tech/mercury-wallet#977]
![Screenshot 2021-12-05 at 17 56 25](https://user-images.githubusercontent.com/7435272/144757831-04a717d1-da72-443a-a3f8-5c20ce730d4e.png)

Wallet has connection issues.

However, it stuck the dialog box and despite clicking [ok], the dialog box keeps on re-appearing and can't get out of a loop.  Have to restart the wallet to get out.

**Comment by lawlawlaw** [comment]
Fixed with https://github.com/layer2tech/mercury-wallet/pull/981
