### ISSUE TITLE
Statecoin registered for Swap but not showing up in pool

### ISSUE THREAD

**Issue by nicosey** [layer2tech/mercury-wallet#986]
Version 0.4.59 

See Screen shot

![Screenshot 2021-12-07 at 12 14 39](https://user-images.githubusercontent.com/7435272/145027421-9b815737-5f5d-4bc4-878b-c9da9193576d.png)

**Comment by tomt1664** [comment]
Was this after a wallet recovery?
Can you open the console (View -> Toggle Developer Tools) and see if it says anything?
