### ISSUE TITLE
Coin stuck in swap phase 4/4

### ISSUE THREAD

**Issue by tomt1664** [layer2tech/mercury-wallet#987]
<img width="603" alt="Screenshot 2021-12-05 at 00 54 00" src="https://user-images.githubusercontent.com/15906918/145037017-df70e2b7-ab8a-42b7-b189-ce876ad93c80.png">

Same status after several restarts. 

<img width="594" alt="Screenshot 2021-12-05 at 00 54 08" src="https://user-images.githubusercontent.com/15906918/145037073-65023275-cffa-4e06-a51f-68c46d3ad1a3.png">

Seems stuck at `transferFinalize` with 'No data for identifier' server DB error. Could the batch transfer have failed (due to other members of the swap group failing to complete transfer_receiver) and it staying stuck?

<img width="591" alt="Screenshot 2021-12-05 at 00 55 17" src="https://user-images.githubusercontent.com/15906918/145037182-1e7aef73-a9dd-4b1f-babf-518792427a17.png">

**Comment by lawlawlaw** [comment]
Fixed in https://github.com/layer2tech/mercury-wallet/pull/990
